### ISSUE TITLE
Falta dos stakeholders 

### ISSUE THREAD

**Issue by Durvalll** [IF977/oxam#1]
Como eu tinha falado na nossa primeira reunião de alinhamento, os stakeholders devem está no project charted. Fora isso tudo parece ok.

**Comment by ygoleite** [comment]
Ok, estarei alterando isso agora.

**Comment by ygoleite** [comment]
Foi corrigido.

**Comment by Durvalll** [comment]
Na seção de StakeHolders não deve ter vocês, essa informação deve está presente em outra seção como por exemplo "Equipe". Coloque as pessoas que são os patrocinadores ( No caso  Vinicius (e outros professores se tiverem usando esse projeto em outras cadeiras), eu como o monitor da cadeira, os usuários e os beneficiados pelo sistema  )

**Comment by Durvalll** [comment]
Na parte de Stakeholders "Engenharia de software" está escrito errado.

**Comment by ygoleite** [comment]
Issue corrigida, foi acrescentado o 'e' que faltava a palavra 'engenharia'
